apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 4100
    targetPort: 4100
    nodePort: 31110