# kubectl explain deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: elkouria/projectbackend
        ports:
        - containerPort: 7777
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 7777
    targetPort: 7777
    nodePort: 31160
    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: front
        image: elkouria/projectfront
        ports:
        - containerPort: 4100
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 4100
    targetPort: 4100
    nodePort: 31150
---

    
